artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://docs.google.com/spreadsheets/d/1D-4AcLhJMOqEBKynFt8pzwGH7cddRuOm/export?format=xlsx
  local_data_file: artifacts/data_ingestion/sample_data__technical_assessment.xlsx

data_validation:
  root_dir: artifacts/data_validation
  local_data_file: artifacts/data_ingestion/sample_data__technical_assessment.xlsx
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_file: artifacts/data_ingestion/sample_data__technical_assessment.xlsx
  train_file: artifacts/data_transformation/train.csv
  test_file: artifacts/data_transformation/test.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_file: artifacts/data_transformation/train.csv
  model_1: artifacts/model_trainer/model_1.pkl
  model_1_scaler: artifacts/model_trainer/model_1_scaler.pkl
  model_2: artifacts/model_trainer/model_2.pkl

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_file: artifacts/data_transformation/test.csv
  model_1: artifacts/model_trainer/model_1.pkl
  model_1_scaler: artifacts/model_trainer/model_1_scaler.pkl
  model_2: artifacts/model_trainer/model_2.pkl
  model_1_stats: artifacts/model_evaluation/model_1_stats
  model_2_stats: artifacts/model_evaluation/model_2_stats
