artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://docs.google.com/spreadsheets/d/1D-4AcLhJMOqEBKynFt8pzwGH7cddRuOm/export?format=xlsx
  local_data_file: artifacts/data_ingestion/sample_data__technical_assessment.xlsx

data_validation:
  root_dir: artifacts/data_validation
  local_data_file: artifacts/data_ingestion/sample_data__technical_assessment.xlsx
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_file: artifacts/data_ingestion/sample_data__technical_assessment.xlsx
  train_file: artifacts/data_transformation/train.csv
  test_file: artifacts/data_transformation/test.csv

